workflows:
  flutter-workflow:
    name: Flutter Workflow
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Fetch dependencies
        script: flutter pub get
      - name: Run tests
        script: flutter test
      - name: Build ipa for distribution
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/xcarchive/*.xcarchive.zip
