workflows:
  ios-app-workflow:
    name: iOS Application
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Fetch dependencies
        script: flutter pub get
      - name: Build IPA for distribution
        script: flutter build ios --release
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/*.ipa
