workflows:
  ios-app-workflow:
    name: iOS Application
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Fetch dependencies
        script: flutter pub get
      - name: Build IPA for simulator (not for real device)
        script: flutter build ios --simulator --debug
    artifacts:
      - build/ios/iphonesimulator/*.app
